### PR TITLE
Jumpbox role

### PR DESCRIPTION
**Pull request by adborden**
Updates the jumpbox role, makes it more compatible for use with packer.

I think I'm going to pull this out into it's own repo after this is merged.

### CODE REVIEW

**Comment by adborden** [comment]
@JJediny is the `AllowUser` directive in the SSH config required for compliance? I think I need to tweak this to allow for non-operator users like the secops user and the ubuntu user.

**Review by JJediny — CHANGES_REQUESTED** [review]
We need to add a handler to restart openssh-server after config changes

**Comment by adborden** [comment]
@JJediny did you want to add your config? https://github.com/GSA/datagov-deploy/blob/b733e5e34311155b1a1d33ac29008b086de9fd2f/ansible/group_vars/all.yml#L38

**Comment by adborden** [comment]
Based on the convo with @JJediny , the ssh AllowUser config is not needed for compliance. I've removed it and there's no longer any config changes to ssh, so I removed the restart handler as well. This is ready for another look.

**Review by JJediny — APPROVED** [review]
Looks great ill add my public key as another PR

**Pull request merged**
