### PR TITLE
Feature/egress proxy restarts

### PR DESCRIPTION
**Pull request by robert-bryson**
Starting draft PR for visibility. 

Related to https://github.com/GSA/data.gov/issues/3789

### CODE REVIEW

**Comment by robert-bryson** [comment]
[This run](https://github.com/GSA/data.gov/runs/6326288665?check_suite_focus=true) fail due to the CF credentials not being available in this repo as they are. for example, [in inventory](https://github.com/GSA/inventory-app/blob/main/.github/workflows/restart.yml#L47). I think there are these options:
- someone (with admin that I do not have) adds the credentials to this repo
- move this work to another repo that already is able to use them
- perhaps something else?

I don't have strong feelings about any option, but started working in this repo as it felt like the best fit for this work.

**Comment by nickumia-reisys** [comment]
I just created new `ci-deployer`s in `development-egress`, `staging-egress`, `prod-egress`,
```
cf create-service cloud-gov-service-account space-deployer ci-deployer
```

Docs: https://cloud.gov/docs/services/cloud-gov-service-account/

**Review by btylerburton — APPROVED** [review]
LGTM 👍🏼

**Review by jbrown-xentity — APPROVED** [review]
Could we add documentation for this in the wiki?

**Comment by robert-bryson** [comment]
> Could we add documentation for this in the wiki?

Yeah, absolutely. Thanks for the reminder!

**Pull request merged**
