### PR TITLE
Build shared python

### PR DESCRIPTION
**Pull request by adborden**
Fixes https://github.com/GSA/catalog-app/issues/76
Compile Python with `--enable-shared` so mod_wsgi works properly.

Adds a CI task to run test-kitchen for the ubuntu/apache roles. I will probably extract this out to its own role, or possibly to [datagov-deploy-ckan-common](https://github.com/GSA/datagov-deploy-ckan-common).

### CODE REVIEW

**Review by JJediny — CHANGES_REQUESTED** [review]
Please remove the test-kitchen work from this PR, it belongs in https://github.com/gsa/datagov-deploy-apache2. Otherwise LGTM

**Comment by adborden** [comment]
:+1: I moved the changes to https://github.com/GSA/datagov-deploy-apache2 and will update this PR to include the new role.

**Comment by adborden** [comment]
This is ready for another look.

**Review by JJediny — APPROVED** [review]
LGTM

**Pull request merged**
