### PR TITLE
archiver

### PR DESCRIPTION
**Pull request by John123Yu**
This branch includes changes needed for archiver,qa pluggins

### CODE REVIEW

**Comment by JJediny** [comment]
@FuhuXia this looks good to me, but ill leave it to you to merge to make sure...

@John123Yu in the future make sure to add me as reviewer to any PR

**Comment by FuhuXia** [comment]
Since we are sharing one redis server across multiple instances, the redis host should be put into an ansible var, not hard coded to be `localhost`.

**Review by FuhuXia — DISMISSED** [review]
Since we are sharing one redis server across multiple instances, the redis host should be put into an ansible var, not hard coded to be `localhost`.

**Comment by John123Yu** [comment]
@JJediny Sure, I will make sure to add you from now on. Would you like to be added as a reviewer for all repositories or ones that pertain to ansible?

**Review by JJediny — APPROVED** [review]
Looks like redis was moved to a var LGTM

**Pull request merged**
