### PR TITLE
Dev catalog fixes

### LINKED ISSUE #386: Ansible cannot create setup/tmp files for an unprivileged user
This task uses `become_user: postgres` to setup postgres users. Ansible 2.5.4 is complaining:

```
TASK [software/catalog/ckan-db-setup : create geo.gov role if missing] ********************************************************
fatal: [catalog-web1t.datagov.us]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of ‘/var/tmp/ansible-tmp-1534457656.68-24692524094148/’: Operation not permitted\nchown: changing ownership of ‘/var/tmp/ansible-tmp-1534457656.68-24692524094148/postgresql_user.py’: Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

See https://docs.ansible.com/ansible/latest/user_guide/become.html#becoming-an-unprivileged-user for potential work arounds.

### PR DESCRIPTION
**Pull request by adborden**
When testing the updated upgrade-python/apache/redis roles in the test and dev environment, I found a handful of issues.

- Ensure existing non-shared python is rebuilt as shared.
- Move saml2 dependencies to catalog-app instead of being installed at deploy time. This makes it easier to test different versions of dependencies actually work together.

This work depends on:
- [x] https://github.com/GSA/catalog-app/pull/79

Fixes #386 #389 

Playbooks tested:
- [x] catalog on catalog-web
- [x] catalog on catalog-harvester
- [x] inventory on inventory-web

### CODE REVIEW

**Comment by adborden** [comment]
Replaces https://github.com/GSA/datagov-deploy/pull/385

**Comment by adborden** [comment]
@JJediny this is ready for review

**Review by JJediny — APPROVED** [review]
👍

**Comment by adborden** [comment]
This should be applied to production:
- [ ] catalog.yml on catalog-web
- [ ] catalog.yml on catalog-harvesters
- [ ] inventory.yml on inventory-web

**Pull request merged**
