### PR TITLE
No apache2 on harvester

### PR DESCRIPTION
**Pull request by vasili4**

### CODE REVIEW

**Comment by FuhuXia** [comment]
We have a playbook for ckan apache. 
https://github.com/GSA/catalog-deploy/tree/master/ansible/roles/software/ckan/apache
do you want to move the code there?

**Comment by vasili4** [comment]
one of the steps changes code at `src/ckan/ckan/lib/base.py`. If I move it to apache role, the further code deployment will rewrite my change.

**Comment by FuhuXia** [comment]
I see. any reason why the code change does not go to ckan repo but modified here with playbook?

https://github.com/GSA/ckan/tree/2.3-upgrade

**Comment by vasili4** [comment]
to simplify future core updates of course

**Comment by FuhuXia** [comment]
Ok. as long as we remember we modify the code in the playbook, and a few months down the line we don't scratch our head wondering why the ckan code on the server does not show up clean with 'git status' check.

**Review by FuhuXia — APPROVED** [review]

**Pull request merged**
