### PR TITLE
add more to staging and develop allow list from prod

### PR DESCRIPTION
**Pull request by FuhuXia**
get new entries from prod and add to staging/development

### CODE REVIEW

**Review by nickumia-reisys — CHANGES_REQUESTED** [review]
Can we make these lists alphabetical, so that it's easier to read? 👀

**Comment by robert-bryson** [comment]
> Can we make these lists alphabetical, so that it's easier to read? 👀

I sorted them with `cat <file> | sort --output=<file>`

**Review by robert-bryson — APPROVED** [review]

**Review by btylerburton — APPROVED** [review]

**Review by nickumia-reisys — APPROVED** [review]
👀 👀

**Comment by FuhuXia** [comment]
can we sort it by domain name, regardless of sub-domain, so that opendataphilly.org and www.opendataphilly.org stay next to each other.

**Pull request merged**
