### PR TITLE
Harvester restart

### PR DESCRIPTION
**Pull request by FuhuXia**
# Pull Request

Related to https://github.com/GSA/data.gov/issues/4187

## About

Added running harvester check
renamed file `bin/check-running-job → bin/check-and-restart`

The git diff make it looks like a file overwritten, but if you look at the commits, you will see changes.

## PR TASKS

- [x] The actual code changes.
- [x] ~Tests written and passed.~
- [x] ~Any changes to docs?~
- [x] ~Any dependent PRs needed?~

### CODE REVIEW

**Comment by robert-bryson** [comment]
Great work, @FuhuXia! 

Since it is a string anyways, do you mind if I rename `ok_to_restart="0"` to like `ok_to_restartr="ok/not_ok"` or something explicit like that?

**Comment by FuhuXia** [comment]
@robert-bryson Thanks for the advice. I changed it to YES/NO

**Comment by FuhuXia** [comment]
Action results verified.

In action https://github.com/GSA/catalog.data.gov/actions/runs/4257406324/jobs/7407498393#step:4:85, it restarted idling fetch. 

In the following action https://github.com/GSA/catalog.data.gov/actions/runs/4257443155/jobs/7407575946#step:4:84, it detected fresh log and skipped restarting on fetch.

**Review by nickumia-reisys — APPROVED** [review]
🧙

**Pull request merged**
